MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #pour que django fasse la difference entre les deux views et savoir lequel des deux choisir
from .forms import LoginFrom
from .import views


app_name= 'accounts'

urlpatterns = [
	#Leave as empty string for base url
  path('register/',views.register,name="register"), 
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True,authentication_form=LoginFrom),name="login"),
  path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html',next_page='accounts:login'),name="logout")
  ]

posts/urls.py
from django.urls import path

from . import views


app_name= 'posts'

urlpatterns = [
	#Leave as empty string for base url
	path('', views.home, name="home"),
  path('post/<int:id>/', views.show, name="show"),
  path('new_post', views.news_post, name="new_post"), 
  path('update_post/<int:id>/',views.update_post,name="update_post"), 
  path('delete_post/<int:id>/',views.delete_post,name="delete_post"),
  path('search_posts/',views.search_posts,name='search_posts')
  ]

templates/layouts/partials/footer.html
<p class="text-center text-light ">
    Copyright &copy;{% now "y" %} &middot;  Myblog.
</p>

templates/layouts/partials/header.html
<nav class="navbar navbar-expand-lg navbar-dark mb-4 shadow">
    <div class="container">
        <div class="container-fluid ">
              <a class="navbar-brand" href="#">Myblog</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                  {% comment %} ici on peut utliser request.user.username pour afficher le nome d'utilisateur sur 
                  sa page d'acceuil. oubien d'autre information de utilisateur  {% endcomment %}


                    {% if request.user.is_authenticated %} 
                <li class="nav-item">
                  <a class="nav-link text-white " aria-current="page" href=" {% url 'posts:home' %} ">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href=" {% url 'posts:new_post' %} ">New Post</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'accounts:logout' %}" >Logout</a>
                </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="#" >Login</a>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="{% url 'accounts:register' %}" >Sign Up</a>
                    </li>
                  </li>
                {% endif %} 
              </ul>
              <form action="{% url 'posts:search_posts' %}" method="get" class="d-flex ml-3" >
                <input placeholder="Search" class="form-control me-3" type="search" name="search">
                <button class="btn btn-outline-light ml-2" type="submit">Search</button>
            </form>
            </div>
            


     </div>
 </nav>

    