MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views


app_name= 'posts'

urlpatterns = [
	#Leave as empty string for base url
	path('', views.home, name="home"),
  path('post/<int:id>/', views.show, name="show"),
  path('new_post', views.news_post, name="new_post"), 
  path('update_post/<int:id>/',views.update_post,name="update_post"), 
  path('delete_post/<int:id>/',views.delete_post,name="delete_post"),
  path('search_posts/',views.search_posts,name='search_posts')
  ]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title=models.CharField(max_length=50)
    content=models.TextField()
    image=models.ImageField(upload_to="posts_image/")
    user=models.ForeignKey(User,on_delete=models.CASCADE) #c'est pour gerer les permission. foreingkey permet OneToMany
    
    
    def __str__(self):
        # return f'Titre:{self.title}'
        return self.title

posts/forms.py
from .models import Post
from django import forms

class PostForm(forms.ModelForm):
    title= forms.CharField(max_length=50,widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    content=forms.CharField(label='Content ',widget=forms.Textarea(attrs={
        'class':'form-control'
    }))
    class Meta:
        model=Post
        fields=('title','content','image') # on enleve user pour permettre a ce que une fois que
                                          #l'utilisateur remplie c'est son nom qui s'affiche lui mm ne va pas remplir son nom

posts/views.py
from django.shortcuts import render,redirect
from .models import Post
from .forms import PostForm
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator


#Un decorateur pour mettre que si l'utilisateur n'est pas connexte il n'pas la pas inedex.html

from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def home(request):
    posts=Post.objects.order_by('-id').all()
    paginator=Paginator(posts,3)
    
    page_number= request.GET.get('page')
    page_object = paginator.get_page(page_number)
    
    posts_number=Post.objects.count()
    message=f'{posts_number} posts: '
    
    if posts_number ==1:
        message=f'{posts_number} post: '
    
    context={
        'posts':page_object,
    
        'message':message
        
    }
    return render(request,'posts/index.html',context)

@login_required
def show(request, id):
    post=Post.objects.get(id=id)
    context={
        
        'post':post,
    }
    
    return render(request,'posts/show.html',context)

@login_required
def news_post(request):
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES)  #request.FILES permet de faire une requete de type get sur les fichiers
                                                    #sans elle on pourra pas soumettre notre formulaire de creation avec une image.        
        if form.is_valid():
            form=form.save(commit=False) # commmit est par defaut a true,si on a le met a false on va d'abord enregistrer 
                                          #le formulaire dans une variable avant de l'enregistrer dans la base de donnee.           
            form.user= request.user     #resquest.user permet de renvoyer l'utilsateur connectee.
            form.save()
            return redirect('posts:home')
    else:
        form=PostForm()        
    context={
        'form':form,
    }
    return render(request,'posts/new_post.html',context)

def update_post(request,id):
    post=Post.objects.get(id=id)
    if post.user == request.user :
        if request.method=='POST':
           form=PostForm(request.POST,request.FILES,instance=post)
           if form.is_valid():
             form.save()              
             return redirect('posts:home')
        else:
         form=PostForm(instance=post)
    else:
        raise Http404    
            
        
    context={
        'form':form,
        'post':post,
    }
    return render(request,'posts/update.html',context)


def delete_post(request,id):
    post=Post.objects.get(id=id)
    if post.user == request.user:
      post.delete()
    # return render(request,'posts/delete_post')
      return redirect('posts:home')
    else:
        raise Http404 # raise permet d'nvoyer une erreur en ptyhon. Toute cette condtion if permet de renforcer la securite de la permission.
    
@login_required    
def search_posts(request):
    search=request.GET.get('search') # le nom defini dans le formulaire pour search sera passe en parametre de get().
    posts= Post.objects.filter(Q(title__icontains= search) |
                               Q(content__icontains= search) |
                               Q(image__icontains= search))
    
    posts_number=posts.count()
    message = f'{posts_number} Resulats: '
    
    if posts_number ==1:
        message = f'{posts_number} Result: '
    context={
        'message':message,
        'posts':posts
    }
    return render(request,'posts/search_posts.html',context)
        

posts/templates/posts/index.html
{% extends 'posts/layouts/base.html' %}
{% load static %}
  
{% block title %}All posts{% endblock title %}


{% block body %}

<h3 class="text-center"> {{ message }} </h3>


<div class="row row-cols-md-3 row-cols-sm-2">
    {% for post in  posts %}
    <div class="col">
        <div class="card mb-3 shadow">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"> {{post.title}} </h5>
                <p class="card-text"> {{ post.content | truncatechars:"100"}} </p> 
                {% comment %} c'est pour limiter les phrases on a utiliser truncatechars:"notre_de_mots" {% endcomment %}
                <a href="  {% url 'posts:show' post.id %} " class="btn btn-primary" >Learn More</a>
                {% if post.user == request.user %}
                  <a href="  {% url 'posts:update_post' post.id %} " class="btn btn-info" >Update</a>
                   <a href="  {% url 'posts:delete_post' post.id %} " class="btn btn-danger" >Delete Post</a>
                {% endif %}
            </div>
            <div class="card-footer">
                <h3>Created by: {{  post.user.username }}  </h3>
                 
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<nav>
    <ul class="pagination justify-content-center">
     {% if posts.has_previous %}
     <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number }}"> &laquo; </a>
        <span aria-hidden="true"></span>
    </li>
     {% endif %}
     <li class="page-item"><p class="page-link text-muted">Page {{ posts.number }} / {{ posts.paginator.num_pages }}. </p></li>

     {% if posts.has_next %}
     <li class="page-item">
         <a class="page-link" href="?page={{ posts.next_page_number }}"> &raquo; </a>
         <span aria-hidden="true"></span>
     </li>
     {% endif %}
    </ul>
</nav>

{% endblock body %}

posts/templates/posts/new_post.html
{% extends 'posts/layouts/base.html' %}

  
{% block title %}New Post{% endblock title %}

{% block body %} 

  <h1 class="text-center mb-3">News post</h1>

 <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.subject.errors %}
            
                    {% for error in form.subject.errors  %}
                  <p class="text-danger">
                    <strong>{{ error }} </strong>
                  </p>
                {% endfor %}
            {% endif %}
            
            {% for field in form %}
            
            <div class="form_group">
                 {{ field.label_tag }} 
                 <!-- {% if field.field.required %}
                  <span class="required">
                    *
                  </span> -->
                 {% endif %}
                 {{ field }}
                {% if field.help_text %}
                 <p class="help">
                  {{ field.help_text }}
                 </p>
                {% endif %}

                {% if field.errors %}
                    {% for error in field.error %}
                        <p class="text-danger"><strong> {{ error }} </strong></p>
                 {% endfor %}
                
                {% endif %}

            </div>
            {% endfor %}
            <br>  
          <input type="submit" class="btn btn-primary mb-3" value="New Post">
        </form>

          </div>
       </div>
       <div class="col-md-4"></div>
    </div>
{% endblock body %}

posts/templates/posts/search_posts.html
{% extends 'posts/layouts/base.html' %}
{% load static %}
  
{% block title %}Search Posts{% endblock title %}
{% block body %}

<h3 class="text-center"> {{  message}} </h3>
<div class="row row-cols-md-3 row-cols-sm-2">
    {% for post in  posts %}
    <div class="col">
        <div class="card mb-3 shadow">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"> {{post.title}} </h5>
                <p class="card-text"> {{ post.content | truncatechars:"100"}} </p> 
                {% comment %} c'est pour limiter les phrases on a utiliser truncatechars:"notre_de_mots" {% endcomment %}
                <a href="  {% url 'posts:show' post.id %} " class="btn btn-primary" >Learn More</a>
                {% if post.user == request.user %}
                  <a href="  {% url 'posts:update_post' post.id %} " class="btn btn-info" >Update</a>
                   <a href="  {% url 'posts:delete_post' post.id %} " class="btn btn-danger" >Delete Post</a>
                {% endif %}
            </div>
            <div class="card-footer">
                <h6>Created by: {{  post.user.username }}  </h6>
                 
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock body %}

posts/templates/posts/show.html
{% extends 'posts/layouts/base.html' %}


{% block title %}Show
{% endblock title %}


{% block body %}
<h1>Show:</h1>
<div class="card mb-3">
            <img src=" {{ post.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title"> {{ post.title }} </h5>
            <p class="card-text"> {{ post.content }} </p>

            {% comment %} les deux boutons de delete_post et update_post {% endcomment %}
            {% comment %} pour afficher les option delete et update sur des poste qui nous appartient seulemnt. ce sont les permission,on a utilier post.user==request.user {% endcomment %}
           <div>
            {% if post.user == request.user %} 
                <div class="card-footer">
                  <a href="  {% url 'posts:update_post' post.id %} " class="btn btn-info" >Update</a>
                  <a href="  {% url 'posts:delete_post' post.id %} " class="btn btn-danger" >Delete Post</a>
                </div>
                {% endif %}
           </div>
</div>
{% endblock body %}

posts/templates/posts/update.html
{% extends 'posts/layouts/base.html' %}

  
{% block title %} Update Posts {{ post.title }} {% endblock title %}

{% block body %} 
<h1>{{ post }} </h1>
  

<h1 class="text-center mb-3">News post</h1>

<div class="container">
     <div class="row">
       <div class="col-md-8 mx-auto">
       <form action="" method="post" enctype="multipart/form-data">
           {% csrf_token %}
           {% if form.subject.errors %}
           
                   {% for error in form.subject.errors  %}
                 <p class="text-danger">
                   <strong>{{ error }} </strong>
                 </p>
               {% endfor %}
           {% endif %}
           
           {% for field in form %}
           
           <div class="form_group">
                {{ field.label_tag }} 
                <!-- {% if field.field.required %}
                 <span class="required">
                   *
                 </span> -->
                {% endif %}
                {{ field }}
               {% if field.help_text %}
                <p class="help">
                 {{ field.help_text }}
                </p>
               {% endif %}

               {% if field.errors %}
                   {% for error in field.error %}
                       <p class="text-danger"><strong> {{ error }} </strong></p>
                {% endfor %}
               {% endif %}
                

           </div>
           {% endfor %}
           <img class="mb-3" src="{{ post.image.url }}" alt="" width="200"> 
           <br>
           
         <input type="submit" class="btn btn-primary mb-3" value="Update Post">
       </form>

         </div>
      </div>
      <div class="col-md-4"></div>
   </div>



{% endblock body %}